name: Build and Run Docker Container

on:
  push:
    branches:
      - main  # Adjust if you're using a different branch

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-node-app .

      - name: Run Docker container
        run: |
          docker run -d \
            --name my-running-app \
            -e NODE_ENV=production \
            -e NETLIFY_PERSONAL_ACCESS_TOKEN=${{ secrets.NETLIFY_PERSONAL_ACCESS_TOKEN }} \
            -e GMAIL_APP_PASSWORD=${{ secrets.GMAIL_APP_PASSWORD }} \
            -e NETLIFY_SITE_ID=${{ secrets.NETLIFY_SITE_ID }} \
            my-node-app

      - name: Show running containers (optional)
        run: docker ps
